name: qr_patrol
description: QR Patrol App MVP
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.20.0
  cloud_firestore: ^4.17.5   # compatible with Flutter 3.x

  google_maps_flutter: ^2.3.0 # compatible with Flutter 3.x

  # QR code scanning
  # qr_code_scanner: ^1.0.1  # not comaptible with web, so we will use mobile_scanner: ^3.5.6  for web support
  mobile_scanner: ^3.5.6   # compatible with Flutter 3.x and supports web

  # Geolocation (compatible with Flutter 3.x)
  geolocator: ^10.1.0

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true