// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8gVJjMzGxEVktNL8IYvdtZX8HmDsPZy8',
    appId: '1:348643580471:web:416fd8a8444e28f63a3db2',
    messagingSenderId: '348643580471',
    projectId: 'residence-patrol',
    authDomain: 'residence-patrol.firebaseapp.com',
    storageBucket: 'residence-patrol.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7ZETyAxltZc9fByAZmTlxUzSB6oIJ7k',
    appId: '1:348643580471:android:e843c5e131bea1ab3a3db2',
    messagingSenderId: '348643580471',
    projectId: 'residence-patrol',
    storageBucket: 'residence-patrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58O2hBqnLZkN30ZZ9NiXDVgvWhECcSL4',
    appId: '1:348643580471:ios:e1efca302e641cfe3a3db2',
    messagingSenderId: '348643580471',
    projectId: 'residence-patrol',
    storageBucket: 'residence-patrol.firebasestorage.app',
    iosBundleId: 'com.example.qrPatrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58O2hBqnLZkN30ZZ9NiXDVgvWhECcSL4',
    appId: '1:348643580471:ios:e1efca302e641cfe3a3db2',
    messagingSenderId: '348643580471',
    projectId: 'residence-patrol',
    storageBucket: 'residence-patrol.firebasestorage.app',
    iosBundleId: 'com.example.qrPatrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8gVJjMzGxEVktNL8IYvdtZX8HmDsPZy8',
    appId: '1:348643580471:web:2466d41266e968d23a3db2',
    messagingSenderId: '348643580471',
    projectId: 'residence-patrol',
    authDomain: 'residence-patrol.firebaseapp.com',
    storageBucket: 'residence-patrol.firebasestorage.app',
  );

}